### ISSUE TITLE
Troubles installing via pip

### ISSUE THREAD

**Issue by anastasia-zhukova** [ad-freiburg/whitespace-correction#3]
Hi! I am having trouble installing via pip and getting the following error: 

`ERROR: Cannot install whitespace-correction==0.1.0, whitespace-correction==0.1.1, whitespace-correction==0.1.2, whitespace-correction==0.1.3, whitespace-correction==0.1.4 and whitespace-correction==0.1.5 because these package versions have conflicting dependencies.`

@bastiscode , I saw that you replied to the other issue, could you have a look into this? :) 

Thank you in advance! 
Anastasia

**Comment by ramyologist** [comment]
Hi! I am having the same issue here, would be great if you could take a look at it. Thanks for the great work you do!

Best regards,
Ramy

**Comment by bastiscode** [comment]
I will look into it today.

**Comment by ramyologist** [comment]
Hi there!

I tried to install whitespace-correction via git clone. In the "whitespace-correction.egg-info"-directory I've found a requires.txt file. It lists the following requirements:

text-correction-utils==0.1.4
transformers>=4.26.0

But the latest version of text-correction-utils on github is 0.2.1: [](https://github.com/ad-freiburg/text-utils/blob:main/python/text_utils/version.py)(https://github.com/ad-freiburg/text-utils/blob:main/python/text_utils/version.py)

This seems to be a problem because, if I see it correctly, the module is not loaded via pip, but via GitHub: [](https://github.com/ad-freiburg/whitespace-correction/blob/main/.gitmodules)(https://github.com/ad-freiburg/whitespace-correction/blob/main/.gitmodules)

I think one should modify the requires.txt accordingly. But when I try to do that manually, it doesn't work because the file is protected.

I hope this information helps somehow.

Best regards,
Ramy

**Comment by bastiscode** [comment]
Yes I worked on an update for the text utils package. Once this is finished I will port the code in this repository to use the new version and make a new release which hopefully also solves your installation problems.

**Comment by ramyologist** [comment]
Great, thank you!🙏

**Comment by bastiscode** [comment]
I just released a new version, 0.2.0, which should fix the installation and other issues.
